name: example
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_spinkit:
    path: ../
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
