name: example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_spinkit:
    path: ../

flutter:
  uses-material-design: true
